### ISSUE TITLE
Error when running cv.polywog

### ISSUE THREAD

**Issue by rotifergirl** [brentonk/polywog#12]
Hi,

I've tried running cv.polywog but I can't figure out what is causing this error.
My data are just a dataframe 

I run:
`cv.polywog(y_dat~x_dat, data=forpoly, degrees.cv = 1:10, nfolds = 5)`

and the error I get is:

>  Error in { : 
>   task 1 failed - "x should be a matrix with 2 or more columns"

I tried inputing my data as a matrix instead, but then got an error that my data should be a dataframe. Any assistance resolving this would be great! Thanks!

Julie

**Comment by brentonk** [comment]
Hi Julie -- without knowing what your data looks like, it's hard to diagnose what's going on here. Can you provide a self-contained minimal example of the problem? Or if your data can be shared, you can email me and I can try to help from there.

**Comment by rotifergirl** [comment]
Sorry Im only getting back to this now! It seems to be some sort of error with some intermediate step of cv.polywog itself, I can email you my data for sure though!

**Comment by brentonk** [comment]
OK, I think the problem is actually inheriting from `glmnet()`, which is called in the innards of `cv.polywog()`. For whatever reason (unclear to me) `glmnet()` won't run on a single-column matrix. I can't change that since it's from imported code. If you change the argument to `degrees.cv = 2:10` it should run without an error.
